version: '3.8'

services:
  acac:
    build: .
    ports:
      - "3000:3000"
    container_name: acac-server
    restart: always
    depends_on:
      - acac-api

  db:
    image: postgres:15
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      retries: 5

  acac-api:
    build: ./acac-api
    container_name: acac-api
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3001:3001"
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: postgres
    volumes:
      - ./acac-api:/app
    command: ["sh", "-c", "sleep 5 && node server.js"]

volumes:
  postgres_data:
